### ISSUE TITLE
1.16 breaks bold formatting

### ISSUE THREAD

**Issue by Smile4ever** [mate-desktop/mate-notification-daemon#111]
I just got the upgrade to MATE 1.16. Notification text between `<b></b>` is no longer displayed bold. Instead, the codes and the text are displayed as notification: `<b>New song reported by VLC</b>`. I expect the text to be `New song reported by VLC` without the formatting codes.

I use Manjaro Linux.

**Comment by kmyid** [comment]
I have the same problem on Arch linux

**Comment by monsta** [comment]
@kajzersoze: could this be a side effect of https://github.com/mate-desktop/mate-notification-daemon/pull/107 and/or https://github.com/mate-desktop/mate-notification-daemon/pull/110?

**Comment by Smile4ever** [comment]
https://github.com/mate-desktop/mate-notification-daemon/pull/107/commits/f95d699d693d3781a15c90a04bc63ad62897eb48 looks suspicious

**Comment by kajzersoze** [comment]
Indeed, it's #107, I'll post a fix in a min.

**Comment by kajzersoze** [comment]
@monsta, problem is in g_markup_escape_text , for some reason it doesn't like `<b>` 
I can't fix it atm, you can revert that commit along with #110 and then bold text will work, but you will then have old problem back, empty notifications when there's a & char in the string, there are also other chars which will cause empty notification to show.
For example : 
$ notify-send "Test" "Test & Example"

will show just "Test" as a title but with no body (Test & Example), instead body would be empty.

I just checked the same function in gnome and it's basically the same thing :
https://github.com/GNOME/notification-daemon/blob/ea34bf17525c2fd5329e34cce1a102766f1a1e0d/src/nd-bubble.c#L616-L668

They have :
```
                tmp = g_markup_escape_text (body, -1);
                gtk_label_set_text (GTK_LABEL (bubble->priv->body_label), body);
                g_free (tmp);
```

but tmp is not used, thus g_markup_escape_text is not used, but they use gtk_label_set_text instead of gtk_label_set_markup (used in mate) and gtk_label_set_text does what g_markup_escape_text is doing, I tested all that, in any case <b> is still shown either way.
Maybe this is all confusing and the only way would be for someone to actually try this in order to understand.

I don't know how to solve this  and like I said.. you can revert that commit and bold text will work but there would be other problems.
Up to you, I'm sorry :disappointed:

**Comment by kajzersoze** [comment]
Had some time today to play with this.. actually the way this is done in gnome works, I just tested it both with vlc and other combinations, everything seems to be working fine. So I will adjust all themes and make a PR, hopefully this will settle this issue once and for all :smiley:

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-notification-daemon/commit/3fa974b37a629eab3668b2565dd0c59dbe38c1a8
Thanks a lot
I will cherry-pick it to 1.16.
