### ISSUE TITLE
mate-notification-daemon fails to start on fedora f28 if multiple Desktops (mate, kde,gnome)

### ISSUE THREAD

**Issue by stevef9432203** [mate-desktop/mate-notification-daemon#133]
#### Expected behaviour
Expect mate-notification daemon to start allowing notify-send to function

#### Actual behavior
Mate-notification daemon never starts

#### Steps to reproduce the behaviour
Installed F27 upgrade to F28 then  sudo dnf groupinstalll  "Mate Desktop"

#### MATE general version
v 1.20

#### Package version
mate-notification-daemon.x86_64       1.20.0-1.fc28           @fedora

**Comment by lukefromdc** [comment]
Works fine on my machine using Debian Unstable. I think the daemon is only supposed to start when a notification is actually sent. See if it is actually functional on your machine: open to mate-control-center, open "popuip notifications: and click the "preview" button. You should see a "Notification Test" popup on your screen at the position shown in the "position" button. You can select any of the four corners of the screen, and one of four themes. If you get NO popup notification on "preview" than the daemon is not starting when a notification is sent to it either.  

I saw on another issue report that dbus is used to activate this as needed, and it exits when the notification is done, rather than running as a fulltime daemon.

**Comment by raveit65** [comment]
Did you file out a redhat bugzilla report?
Do you have kde installed?

**Comment by raveit65** [comment]
Using notify-send from command line forks here out of box in f28.
Eg. 
```
[rave@mother ~]$ notify-send Hello
```

**Comment by hkoba** [comment]
Hi! I'm using MATE desktop since 2013 and I love it! Thank you, teams!

This issue is one of the most annoying problems in MATE.
I also suffered from this problem since F28. And the problem persists still on F32 too. 

Fortunately, the following workaround I found today worked for me:

```console
mkdir -p ~/.local/share/dbus-1/services/

ln -vnsfr $(rpm -ql mate-notification-daemon|grep Notifications.service)  ~/.local/share/dbus-1/services/org.freedesktop.Notifications.service

```

Hope this helps.

**Comment by lukefromdc** [comment]
Note that I do NOT have kde installed, so might have avoided the race condition, assuming some difference in Debian would not prevent it anyway

**Comment by raveit65** [comment]
Will be fixed with https://github.com/mate-desktop/mate-notification-daemon/pull/214
