### ISSUE TITLE
GTK3: regression with bg color of slider theme

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-notification-daemon#85]
Slider theme does not draw the correct bg color from gtk theme.
Means, if you change the gtk theme than the bg in notification theme should change too.
Currently the bg color is black, but with normal fg color (black) from most themes you can't read nothing.
The culprit is https://github.com/mate-desktop/mate-notification-daemon/commit/0fb782d2dcc129ab0858ea0d4399f6c183cb20c1
Reverting this commit with git rebase works cleanly and fixes the issue.
I want to revert this commit for 1.12 because slider is the only theme which works correctly with gtk3.
We can fix the deprecated commit later, after 1.12 release.
@GiedriusS 
@monsta 
@flexiondotorg 
@clefebvre 
What do you think about and can you give me a GO ?

**Comment by monsta** [comment]
Since it affects GTK+3 only I don't mind.

**Comment by raveit65** [comment]
Ok, i will revert the commit

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-notification-daemon/commit/076f60875f1dc47b6d5fc34f6c007976fd0947cb

**Comment by zhiouneoj** [comment]
@raveit65 

Slider has been black _**with white text**_ for as long as I've used it and hasn't been a problem. I just upgraded from Fedora 22 to 24 and now Slider is gray with black text -- not only do I think this looks bad, but the notifications don't catch my eye nearly as much, as it blends in with other windows (see screen capture below). Is there a way for me to get this to show up black again (even if by editing a theme, so long as it doesn't change e.g. my windows to black as well)?

![slider-gray](https://cloud.githubusercontent.com/assets/20467234/16859719/2fdfd22e-49ff-11e6-8ed1-66f10e0b7604.png)

**Comment by raveit65** [comment]
Slider works correct now as it is for gtk3. You can use coco theme which black with white text.

**Comment by monsta** [comment]
Slider now uses fg/bg from your GTK+ theme as is, no more reverting.

**Comment by zhiouneoj** [comment]
@raveit65 I appreciate the suggestion, but I prefer Slider over Coco, and Coco has it's own problems, new and old ...

Coco has less padding and the padding it does have isn't uniform:
![padding](https://cloud.githubusercontent.com/assets/20467234/17499510/b8038722-5d9b-11e6-9da1-a555d1c740b0.png)
Versus Slider:
![padding-slider](https://cloud.githubusercontent.com/assets/20467234/17499675/e47ebfaa-5d9c-11e6-8c4a-cd08728e429c.png)

Coco has half the space between the notification summary and body -- it looks crammed-together:
![spacing](https://cloud.githubusercontent.com/assets/20467234/17499781/afdf63a2-5d9d-11e6-825b-f30387bce92f.png)
Versus Slider:
![spacing-slider](https://cloud.githubusercontent.com/assets/20467234/17499788/bc2ab968-5d9d-11e6-87c5-c0d651369b8c.png)

Coco is darker than Slider, as can be seen above.
Coco doesn't have the nice subtle border that Slider has.
Coco isn't as wide and looks even more crammed when the message body is longer.
Coco uses white text, rather than the grey text that Slider uses which makes Slider look softer.

Coco just doesn't look as good overall:
![coco](https://cloud.githubusercontent.com/assets/20467234/17499962/5f9a1764-5d9f-11e6-90ec-573543adb844.png)
Slider:
![slider](https://cloud.githubusercontent.com/assets/20467234/17499965/69b673c8-5d9f-11e6-84d1-e39586d3128c.png)

They're subtle but important aesthetic differences and the reason I chose Slider. If you feel that a grey version of Slider is more appealing, could you fork Slider and call is Slider Grey? Slider has been black all along; reversing the colors is making an alteration from one of it's key characteristics :-(
